osx_image: xcode9.4
sudo: false
language: node_js
node_js: "10.0.0"
os:
  - osx

script:
  - "npm test"
  - "npm run generate:config"
  - "npm run release"

before_install:
  - "npm i -g npm@6.4.1"

cache:
  directories:
    - "node_modules"
